# Generated by Django 5.1.4 on 2025-06-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdeletedalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
