# Generated by Django 5.1.4 on 2025-06-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
