# Generated by Django 5.1.4 on 2025-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_privatemessage_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('Visitor Arrival', 'Visitor Arrival'), ('Fire Alarm', 'Fire Alarm'), ('Security Breach', 'Security Breach'), ('others', 'others')], max_length=50),
        ),
    ]
