# Generated by Django 5.1.4 on 2025-06-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
