# Generated by Django 5.1.4 on 2025-07-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signup_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
