# Generated by Django 5.1.4 on 2025-07-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_signup_otp_userprofile_signup_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
