# Generated by Django 5.2.4 on 2025-08-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
