# Generated by Django 5.2.4 on 2025-08-12 13:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_bankservicecharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankservicecharge",
            name="outstanding_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Outstanding Charge in Naira (#)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="bankservicecharge",
            name="paid_charge",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Paid Charge in Naira (#)",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
