# Generated by Django 5.2.4 on 2025-08-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_bankservicecharge_outstanding_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankservicecharge",
            name="receipt_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a receipt image for the payment",
                null=True,
                upload_to="service_charge_receipts/",
            ),
        ),
    ]
