# Generated by Django 5.2.4 on 2025-08-14 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_bankservicecharge_receipt_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lostfounditem",
            name="image",
        ),
        migrations.AlterField(
            model_name="bankservicecharge",
            name="receipt_image",
            field=models.FileField(
                blank=True,
                help_text="Upload any file for the payment",
                null=True,
                upload_to="service_charge_receipts/",
            ),
        ),
        migrations.CreateModel(
            name="BankServiceChargeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload any file for the payment",
                        upload_to="service_charge_receipts/",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank_service_charge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_files",
                        to="accounts.bankservicecharge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LostFoundFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="lostfound_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lost_found_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="accounts.lostfounditem",
                    ),
                ),
            ],
        ),
    ]
