# Generated by Django 5.2.4 on 2025-08-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_remove_lostfounditem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfounditem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="lostfound_images/"
            ),
        ),
        migrations.DeleteModel(
            name="LostFoundFile",
        ),
    ]
