# Generated by Django 5.2.4 on 2025-08-20 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_lostfounditem_image_delete_lostfoundfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devicetoken",
            unique_together={("user", "token")},
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="device_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="platform",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["token"], name="accounts_de_token_6c786c_idx"),
        ),
        migrations.RemoveField(
            model_name="devicetoken",
            name="created_at",
        ),
    ]
