# Generated by Django 5.2.4 on 2025-09-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_devicetoken_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="apartment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("self_contain", "Self-contain"),
                    ("1_bed", "1-Bedroom Flat"),
                    ("2_bed", "2-Bedroom Flat"),
                    ("3_bed", "3-Bedroom Flat"),
                    ("4_bed", "4-Bedroom Flat"),
                    ("5_plus", "5+ Bedroom Flat"),
                ],
                help_text="Type of flat/apartment (e.g., Self-contain, 1-Bedroom Flat)",
                max_length=16,
                null=True,
            ),
        ),
    ]
