# Generated by Django 5.2.4 on 2025-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_userprofile_apartment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lostfounditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
