# Generated by Django 5.2.4 on 2025-09-23 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_alter_lostfounditem_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["item_type", "date_reported"],
                name="accounts_lo_item_ty_eec9ec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lostfounditem",
            index=models.Index(
                fields=["sender", "date_reported"],
                name="accounts_lo_sender__f7e7b8_idx",
            ),
        ),
    ]
